class AuthError {
  final Exception exception;

  AuthError(this.exception);
}
